Web game logic
vtodorchuk/codebreaker-rack pull request #1
Opened 2022-08-15 15:07 UTC by VladyslavTodorchuk

2022-08-25 10:50 UTC, CaptainJNS requested changes

2022-08-25 10:50 UTC, CaptainJNS commented on coverage/.last_run.json
> +{
remove `coverage/`

2022-08-25 10:50 UTC, CaptainJNS commented on spec/middlewares/routes_spec.rb
> +  end
do you need it?

2022-08-25 10:50 UTC, CaptainJNS commented on spec/services/data_spec.rb
> +        data = CodeBreaker::Game.new name: 'Vlad', difficulty: 'easy', secret_code: [1, 1, 1, 1]
use `let`

2022-08-25 10:50 UTC, CaptainJNS commented on spec/services/data_spec.rb
> +      it do
describe tests

2022-08-25 10:50 UTC, CaptainJNS commented on storage/data.yml
> +--- !ruby/object:Entities::Rating
to gitignore

2022-08-26 08:48 UTC, VladyslavTodorchuk commented on spec/middlewares/routes_spec.rb
> +  end
With out this method test won`t pass. 

```
NameError:
        undefined local variable or method `app' for #<RSpec::ExampleGroups::MiddlewaresRoutes::WhenGameStart::WhenReceivedUserParams "redirects to game page" (./spec/middlewares/routes_spec.rb:118)>

```

2022-09-02 13:39 UTC, CaptainJNS approved these changes

2022-09-02 13:40 UTC, CaptainJNS commented
Fix tests. But keep `data.yml` in gitignore

2022-09-02 17:47 UTC, merged